version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d
    environment:
      CLICKHOUSE_DB: sensorhub
      CLICKHOUSE_USER: default  # Используем встроенного пользователя
      CLICKHOUSE_PASSWORD: ""   # Пустой пароль для теста

volumes:
  clickhouse_data: